#define BIT_INIT_FIREBASE (1 << 0)
#define BIT_FIREBASE_LISTENER (1 << 1)
#define BIT_IR_SEND (1 << 2)
#define BIT_IR_RV (1 << 3)
#define BIT_LED_START (1 << 4)
#define BIT_LED_INIT_WIFI (1 << 5)
#define BIT_LED_INIT_FIREBASE (1 << 6)
#define BIT_LED_FIREBASE_WORKING (1 << 7)